version: "3.7"

services:
  hipster.db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"

  hipster.api:
    build:
      context: .
      dockerfile: "api.dockerfile"
    environment:
      ConnectionStrings__Database: "Host=hipster.db;Username=postgres;Password=mysecretpassword"
    ports:
      # Same port as when running locally, for consistency
      - "5000:80"
    depends_on:
      - "hipster.db"

  hipster.app:
    build:
      context: .
      dockerfile: "app.dockerfile"
      args:
        - API_URL=http://localhost:5000
        - APP_URL=http://localhost:3000
    ports:
      - "3000:80"
    depends_on:
      - "hipster.api"